### ISSUE TITLE
eval: add support to multiple statements

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/abad#27]
The following should work:

```js
console.log(1)
console.log(2);
console.log(3);console.log(4)
```

**Comment by ryukinix** [comment]
Just a report here after #29 being merged

![image](https://user-images.githubusercontent.com/7642878/42701284-ac858496-86b5-11e8-8612-71d848a0cb55.png)

Funny behavior. Maybe a problem in the tokenizer? I think `console` is getting a left-leading whitespace.

**Comment by katcipis** [comment]
There is no support for whitespace yet =P

**Comment by ryukinix** [comment]
That makes sense, sorry for reporting in the wrong issue.

**Comment by katcipis** [comment]
No problem man, thanks for reviewing everything so carefully ;-)
